RSystem/Models/Db Models/Specialization.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RSystem.Models
{

    public class Specialization
    {
        public int SpecializationId { get; set; }

        [Required(ErrorMessage = "Nazwa kierunku jest wymagana.")]
        [Display(Name = "Nazwa kierunku.")]
        public string Name { get; set; }

        [Display(Name = "Opis.")]
        public string Description { get; set; }

        [Display(Name = "Opłata")]
        [Required(ErrorMessage = "Opłata rekrutacyjna jest wymagana.")]
        public float Price { get; set; }

        public ICollection<PointsMultipiler> PointsMultipilers { get; set; }
        [Required(ErrorMessage = "Termin zakończenia rekrutacji jest wymagany.")]
        [Display(Name = "Termin zakończenia.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Deadline { get; set; }

        [Required(ErrorMessage = "Wydział jest wymagany.")]
        public int FacultyId { get; set; }
        public Faculty Faculty { get; set; }

        [Required(ErrorMessage = "Limit miejsc jest wymagany")]
        [Display(Name = "Limit miejsc")]
        public int LimitOfPlaces { get; set; }
    
        public ICollection<RecruitPreference> RecruitPreferences { get; set; }

        public ICollection<Recruit> AcceptedRecruits { get; set; }
        
    }
}

RSystem/Areas/Admin/Controllers/SpecializationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RSystem.Areas.Admin.Models;
using RSystem.DAL;
using RSystem.Managers;
using RSystem.Models;

namespace RSystem.Areas.Admin.Controllers
{   
    [Authorize(Roles = "Admin")]    
    public class SpecializationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Specializations       
        public ActionResult Index()
        {
            var model = new Dictionary<Faculty, IEnumerable<Specialization>>();
            var faculties = db.Faculties.Include(s => s.Specializations)
                .OrderBy(s=>s.Abbrevation);            

            foreach (var faculty in faculties)
            {
                if (faculty.Specializations.Any())
                {
                    model.Add(faculty, faculty.Specializations
                        .OrderBy(s=>s.Name));
                }
            }

            return View(model);
        }
        
        // GET: Specializations/Create
        public ActionResult Create(int? id)
        {            
            ViewBag.Title = id==null?
                "Dodaj Kierunek":
                "Edytuj Kierunek";

            var viewModel = new SpecializationCreateViewModel()
            {
                PointsMultipilers =
                    db.PointsMultipilers.Include(ms => ms.MaturaSubject).Where(s => s.SpecializationId == id),
                Faculties = new SelectList(db.Faculties, "FacultyId", "Name"),
                MaturaSubjects = db.MaturaSubjects,
                Specialization = db.Specializations.FirstOrDefault(i => i.SpecializationId == id)

            };
            return View(viewModel);                       
        }

        // POST: Specializations/Create        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SpecializationCreatePOSTViewModel model)
        {
            //SpecializationId is null while creating            
            ModelState["Specialization.SpecializationId"].Errors.Clear();

            if (ModelState.IsValid)
            {
                var specialization = model.Specialization;

                var multipilers = new List<PointsMultipiler>();

                if (!string.IsNullOrWhiteSpace(model.MultipilersJSON))
                    multipilers = JSONParserManager
                        .JsonToPointsMultipilers(model.MultipilersJSON, model.Specialization.SpecializationId)
                        .ToList();

                if (specialization.SpecializationId == 0)
                {
                    specialization.PointsMultipilers = multipilers;
                    db.Specializations.Add(specialization);                    
                }
                else
                {
                    foreach (var multipiler in multipilers)
                        db.PointsMultipilers.Add(multipiler);
                    db.Entry(specialization).State = EntityState.Modified;                    
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(new SpecializationCreateViewModel
            {
                Specialization = model.Specialization,
                Faculties = new SelectList(db.Faculties, "FacultyId", "Name"),
                MaturaSubjects = db.MaturaSubjects,
                PointsMultipilers = db.PointsMultipilers.Include(ms => ms.MaturaSubject)
                    .Where(s => s.SpecializationId == model.Specialization.SpecializationId)
            });
        }
  

        // POST: Specializations/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Specialization specialization = db.Specializations.Find(id);
            db.Specializations.Remove(specialization);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RSystem/Areas/Admin/Views/Specializations/Index.cshtml
@model Dictionary<RSystem.Models.Faculty, IEnumerable<RSystem.Models.Specialization>>

@{
    ViewBag.Title = "Lista kierunków";
}

<div class="add-field text-center my-20">
    @Html.ActionLink("Dodaj kierunek", "Create", "Specializations", null, new { @class = "add-button" })
</div>
@foreach (var faculty in Model)
{
    <section class="faculty ">
        <header>
            @faculty.Key.Name
        </header>
        <div class="table-responsive">
            <table class="main-table table table-striped">
                <tr>
                    <th>Kierunek/Specialność</th>
                    <th>Termin zakończenia</th>
                    <th>Opłata rekrutacyjna</th>
                    <th>Operacje</th>
                    <th>Próg punktowy</th>
                </tr>
                @foreach (var specialization in faculty.Value)
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("Create","Specializations",new{id=specialization.SpecializationId})">
                                <b>
                                    @specialization.Name (@specialization.Faculty.Abbrevation)
                                </b>
                            </a>
                            <br />
                            <span>@specialization.Description</span>
                        </td>
                        <td>
                            @specialization.Deadline.ToString("dd'.'MM'.'yyyy")
                        </td>
                        <td>
                            @specialization.Price zl
                        </td>
                        <td>
                            @using (Html.BeginForm("Delete", "Specializations", FormMethod.Post, new { @class = "js-delete" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.Hidden("id", specialization.SpecializationId)
                                <button type="submit" class=" color-rejected btn-remove">Usuń</button>
                            }

                        </td>

                        <td>0</td>

                    </tr>
                }

            </table>
        </div>
</section>
}


@section DedicatedStyles
{
    <link rel="stylesheet" href="/Content/css/SpecializationIndex.css"/>
}

@section scripts
{
    <script>

        $('.js-delete').submit(function(e) {
            var currentForm = this;
            e.preventDefault();
            bootbox.confirm({
                message: "Czy napewno chcesz usunąć ten kierunek?",
                buttons: {
                    confirm: {
                        label: 'Usuń',
                        className: 'btn-danger'
                    },
                    cancel: {
                        label: 'Anuluj',
                    }
                },
                callback: function(result) {
                    if (result) {
                        currentForm.submit();
                    }
                }
            });
        });

    </script>

}